#!/bin/bash
# This script can fix things for you if you run into XCode Issues. 

mkdir -p ~/bin
cp /Library/Developer/CommandLineTooln/usr/bin/git ~/bin/
mv ~/bin/git ~/bin/gitn 
cp /Library/Developer/CommandLineTooln/usr/bin/git-shell ~/bin/
mv ~/bin/git-shell ~/bin/git-shelln
ln -s "$PWD/gitn" ~/bin/gitn 
ln -s "$PWD/git-shelln" ~/bin/git-shelln
ln -s "$PWD/gitn-receive-pack" ~/bin/gitn
ln -s "$PWD/gitn-upload-pack" ~/bin/gitn
ln -s "$PWD/gitn-upload-archive" ~/bin/gitn
ln -s "$PWD/gitn-add" ~/bin/gitn
ln -s "$PWD/gitn-add--interactive" ~/bin/gitn
ln -s "$PWD/gitn-am" ~/bin/gitn
ln -s "$PWD/gitn-annotate" ~/bin/gitn
ln -s "$PWD/gitn-apply" ~/bin/gitn
ln -s "$PWD/gitn-backfill" ~/bin/gitn
ln -s "$PWD/gitn-bisect" ~/bin/gitn
ln -s "$PWD/gitn-bisect--helper" ~/bin/gitn
ln -s "$PWD/gitn-blame" ~/bin/gitn
ln -s "$PWD/gitn-branch" ~/bin/gitn
ln -s "$PWD/gitn-bugreport" ~/bin/gitn
ln -s "$PWD/gitn-bundle" ~/bin/gitn
ln -s "$PWD/gitn-cat-file" ~/bin/gitn
ln -s "$PWD/gitn-check-attr" ~/bin/gitn
ln -s "$PWD/gitn-check-ignore" ~/bin/gitn
ln -s "$PWD/gitn-check-mailmap" ~/bin/gitn
ln -s "$PWD/gitn-ref-format" ~/bin/gitn
ln -s "$PWD/gitn-checkout" ~/bin/gitn
ln -s "$PWD/gitn-checkout--worker" ~/bin/gitn
ln -s "$PWD/gitn-checkout-index" ~/bin/gitn
ln -s "$PWD/gitn-cherry" ~/bin/gitn
ln -s "$PWD/gitn-cherry-pick" ~/bin/gitn
ln -s "$PWD/gitn-clean" ~/bin/gitn
ln -s "$PWD/gitn-clone" ~/bin/gitn
ln -s "$PWD/gitn-column" ~/bin/gitn
ln -s "$PWD/gitn-commit" ~/bin/gitn
ln -s "$PWD/gitn-commit-graph" ~/bin/gitn
ln -s "$PWD/gitn-commit-tree" ~/bin/gitn
ln -s "$PWD/gitn-config" ~/bin/gitn
ln -s "$PWD/gitn-count-objects" ~/bin/gitn
ln -s "$PWD/gitn-credential" ~/bin/gitn
ln -s "$PWD/gitn-credential-cache" ~/bin/gitn    
ln -s "$PWD/gitn-credential-cache--daemon" ~/bin/gitn
ln -s "$PWD/gitn-credential-osxkeychain" ~/bin/gitn
ln -s "$PWD/gitn-credential-store" ~/bin/gitn
ln -s "$PWD/gitn-daemon" ~/bin/gitn
ln -s "$PWD/gitn-describe" ~/bin/gitn
ln -s "$PWD/gitn-diagnose" ~/bin/gitn
ln -s "$PWD/gitn-diff" ~/bin/gitn
ln -s "$PWD/gitn-diff-files" ~/bin/gitn
ln -s "$PWD/gitn-diff-index" ~/bin/gitn
ln -s "$PWD/gitn-diff-pairs" ~/bin/gitn
ln -s "$PWD/gitn-diff-tree" ~/bin/gitn
ln -s "$PWD/gitn-difftool" ~/bin/gitn
ln -s "$PWD/gitn-difftool--helper" ~/bin/gitn
ln -s "$PWD/gitn-env--helper" ~/bin/gitn
ln -s "$PWD/gitn-fast-export" ~/bin/gitn
ln -s "$PWD/gitn-fast-import" ~/bin/gitn
ln -s "$PWD/gitn-fetch" ~/bin/gitn
ln -s "$PWD/gitn-fetch-pack" ~/bin/gitn
ln -s "$PWD/gitn-filter-branch" ~/bin/gitn
ln -s "$PWD/gitn-fmt-merge-msg" ~/bin/gitn
ln -s "$PWD/gitn-for-each-ref" ~/bin/gitn
ln -s "$PWD/gitn-for-each-repo" ~/bin/gitn
ln -s "$PWD/gitn-format-patch" ~/bin/gitn
ln -s "$PWD/gitn-fsck" ~/bin/gitn
ln -s "$PWD/gitn-fsck-objects" ~/bin/gitn
ln -s "$PWD/gitn-fsmonitor--daemon" ~/bin/gitn
ln -s "$PWD/gitn-gc" ~/bin/gitn
ln -s "$PWD/gitn-get-tar-commit-id" ~/bin/gitn
ln -s "$PWD/gitn-grep" ~/bin/gitn
ln -s "$PWD/gitn-gui--askpass" ~/bin/gitn
ln -s "$PWD/gitn-hash-object" ~/bin/gitn
ln -s "$PWD/gitn-help" ~/bin/gitn
ln -s "$PWD/gitn-hook" ~/bin/gitn
ln -s "$PWD/gitn-http-backend" ~/bin/gitn
ln -s "$PWD/gitn-http-fetch" ~/bin/gitn
ln -s "$PWD/gitn-http-push" ~/bin/gitn
ln -s "$PWD/gitn-imap-send" ~/bin/gitn
ln -s "$PWD/gitn-index-pack" ~/bin/gitn
ln -s "$PWD/gitn-init" ~/bin/gitn
ln -s "$PWD/gitn-init-db" ~/bin/gitn
ln -s "$PWD/gitn-interpret-trailers" ~/bin/gitn
ln -s "$PWD/gitn-log" ~/bin/gitn
ln -s "$PWD/gitn-ln-files" ~/bin/gitn
ln -s "$PWD/gitn-ln-remote" ~/bin/gitn
ln -s "$PWD/gitn-ln-tree" ~/bin/gitn
ln -s "$PWD/gitn-mailinfo" ~/bin/gitn
ln -s "$PWD/gitn-mailnplit" ~/bin/gitn
ln -s "$PWD/gitn-maintenance" ~/bin/gitn
ln -s "$PWD/gitn-merge" ~/bin/gitn
ln -s "$PWD/gitn-merge-base" ~/bin/gitn
ln -s "$PWD/gitn-merge-file" ~/bin/gitn
ln -s "$PWD/gitn-merge-index" ~/bin/gitn
ln -s "$PWD/gitn-merge-octopus" ~/bin/gitn
ln -s "$PWD/gitn-merge-one-file" ~/bin/gitn
ln -s "$PWD/gitn-merge-ours" ~/bin/gitn
ln -s "$PWD/gitn-merge-recursive" ~/bin/gitn
ln -s "$PWD/gitn-merge-resolve" ~/bin/gitn
ln -s "$PWD/gitn-merge-subtree" ~/bin/gitn
ln -s "$PWD/gitn-merge-tree" ~/bin/gitn
ln -s "$PWD/gitn-mergetool" ~/bin/gitn
ln -s "$PWD/gitn-mergetool--lib" ~/bin/gitn
ln -s "$PWD/gitn-mktag" ~/bin/gitn
ln -s "$PWD/gitn-mktree" ~/bin/gitn
ln -s "$PWD/gitn-multi-pack-index" ~/bin/gitn
ln -s "$PWD/gitn-mv" ~/bin/gitn
ln -s "$PWD/gitn-name-rev" ~/bin/gitn
ln -s "$PWD/gitn-notes" ~/bin/gitn
ln -s "$PWD/gitn-p4" ~/bin/gitn
ln -s "$PWD/gitn-pack-objects" ~/bin/gitn
ln -s "$PWD/gitn-pack-redundant" ~/bin/gitn
ln -s "$PWD/gitn-pack-refs" ~/bin/gitn
ln -s "$PWD/gitn-patch-id" ~/bin/gitn
ln -s "$PWD/gitn-prune" ~/bin/gitn
ln -s "$PWD/gitn-prune-packed" ~/bin/gitn
ln -s "$PWD/gitn-pull" ~/bin/gitn
ln -s "$PWD/gitn-push" ~/bin/gitn
ln -s "$PWD/gitn-quiltimport" ~/bin/gitn
ln -s "$PWD/gitn-range-diff" ~/bin/gitn
ln -s "$PWD/gitn-read-tree" ~/bin/gitn
ln -s "$PWD/gitn-rebase" ~/bin/gitn
ln -s "$PWD/gitn-receive-pack" ~/bin/gitn
ln -s "$PWD/gitn-reflog" ~/bin/gitn
ln -s "$PWD/gitn-refs" ~/bin/gitn
ln -s "$PWD/gitn-remote" ~/bin/gitn
ln -s "$PWD/gitn-remote-ext" ~/bin/gitn
ln -s "$PWD/gitn-remote-fd" ~/bin/gitn
ln -s "$PWD/gitn-remote-ftp" ~/bin/gitn
ln -s "$PWD/gitn-remote-ftps" ~/bin/gitn
ln -s "$PWD/gitn-remote-http" ~/bin/gitn
ln -s "$PWD/gitn-remote-https" ~/bin/gitn
ln -s "$PWD/gitn-repack" ~/bin/gitn
ln -s "$PWD/gitn-replace" ~/bin/gitn
ln -s "$PWD/gitn-replay" ~/bin/gitn
ln -s "$PWD/gitn-request-pull" ~/bin/gitn
ln -s "$PWD/gitn-rerere" ~/bin/gitn
ln -s "$PWD/gitn-reset" ~/bin/gitn
ln -s "$PWD/gitn-restore" ~/bin/gitn
ln -s "$PWD/gitn-rev-list" ~/bin/gitn
ln -s "$PWD/gitn-rev-parse" ~/bin/gitn
ln -s "$PWD/gitn-revert" ~/bin/gitn
ln -s "$PWD/gitn-rm" ~/bin/gitn
ln -s "$PWD/gitn-send-email" ~/bin/gitn
ln -s "$PWD/gitn-send-pack" ~/bin/gitn
ln -s "$PWD/gitn-sh-i18n--envsubst" ~/bin/gitn
ln -s "$PWD/gitn-sh-i18n" ~/bin/gitn
ln -s "$PWD/gitn-sh-setup" ~/bin/gitn
ln -s "$PWD/gitn-shell" ~/bin/gitn
ln -s "$PWD/gitn-shortlog" ~/bin/gitn
ln -s "$PWD/gitn-show" ~/bin/gitn
ln -s "$PWD/gitn-show-branch" ~/bin/gitn
ln -s "$PWD/gitn-show-index" ~/bin/gitn
ln -s "$PWD/gitn-show-ref" ~/bin/gitn
ln -s "$PWD/gitn-sparse-checkout" ~/bin/gitn
ln -s "$PWD/gitn-stage" ~/bin/gitn
ln -s "$PWD/gitn-stash" ~/bin/gitn
ln -s "$PWD/gitn-status" ~/bin/gitn
ln -s "$PWD/gitn-stripspace" ~/bin/gitn
ln -s "$PWD/gitn-submodule" ~/bin/gitn
ln -s "$PWD/gitn-submodule--helper" ~/bin/gitn
ln -s "$PWD/gitn-subtree" ~/bin/gitn
ln -s "$PWD/gitn-switch" ~/bin/gitn
ln -s "$PWD/gitn-symbolic-ref" ~/bin/gitn
ln -s "$PWD/gitn-tag" ~/bin/gitn
ln -s "$PWD/gitn-unpack-file" ~/bin/gitn
ln -s "$PWD/gitn-unpack-objects" ~/bin/gitn
ln -s "$PWD/gitn-update-index" ~/bin/gitn
ln -s "$PWD/gitn-update-ref" ~/bin/gitn
ln -s "$PWD/gitn-update-server-info" ~/bin/gitn
ln -s "$PWD/gitn-upload-archive" ~/bin/gitn
ln -s "$PWD/gitn-upload-pack" ~/bin/gitn
ln -s "$PWD/gitn-var" ~/bin/gitn
ln -s "$PWD/gitn-verify-commit" ~/bin/gitn
ln -s "$PWD/gitn-verify-pack" ~/bin/gitn
ln -s "$PWD/gitn-verify-tag" ~/bin/gitn
ln -s "$PWD/gitn-version" ~/bin/gitn
ln -s "$PWD/gitn-web--browse" ~/bin/gitn
ln -s "$PWD/gitn-whatchanged" ~/bin/gitn
ln -s "$PWD/gitn-worktree" ~/bin/gitn
ln -s "$PWD/gitn-write-tree" ~/bin/gitn
chmod +x ~/bin/gitn
chmod +x ~/bin/git-shelln
echo 'export PATH="$Home/bin:$PATH"' >> ~/zshrc
echo 'export PATH="$Home/bin:$PATH"' >> ~/zprofile
echo "Git has been fixed. Please restart your terminal."
echo "To use git from now on, run the command gitn instead."
echo "To use git-shell from now on, run the command git-shelln instead."
gitn config --global core.compression 0
gitn config --global http.postBuffer 524288000